const { protect, optionalAuth, authorize, authorizeOwnerOrAdmin, refreshToken } = require('./auth');
const { AppError, errorHandler, notFound, asyncHandler } = require('./errorHandler');
const {
  handleValidationErrors,
  registerValidation,
  loginValidation,
  forgotPasswordValidation,
  resetPasswordValidation,
  changePasswordValidation,
  updateProfileValidation,
  updateAddressValidation,
  createArtisanValidation,
  updateArtisanValidation,
  updateAvailabilityValidation,
  createBookingValidation,
  updateBookingStatusValidation,
  cancelBookingValidation,
  createReviewValidation,
  initializePaymentValidation,
  sendMessageValidation,
  createCategoryValidation,
  paginationValidation,
  searchValidation,
  mongoIdParamValidation,
} = require('./validation');
const {
  apiLimiter,
  authLimiter,
  registerLimiter,
  passwordResetLimiter,
  bookingLimiter,
  paymentLimiter,
  messageLimiter,
  reviewLimiter,
  webhookLimiter,
  adminActionLimiter,
} = require('./rateLimiter');

module.exports = {
  // Auth middleware
  protect,
  optionalAuth,
  authorize,
  authorizeOwnerOrAdmin,
  refreshToken,

  // Error handling
  AppError,
  errorHandler,
  notFound,
  asyncHandler,

  // Validation
  handleValidationErrors,
  registerValidation,
  loginValidation,
  forgotPasswordValidation,
  resetPasswordValidation,
  changePasswordValidation,
  updateProfileValidation,
  updateAddressValidation,
  createArtisanValidation,
  updateArtisanValidation,
  updateAvailabilityValidation,
  createBookingValidation,
  updateBookingStatusValidation,
  cancelBookingValidation,
  createReviewValidation,
  initializePaymentValidation,
  sendMessageValidation,
  createCategoryValidation,
  paginationValidation,
  searchValidation,
  mongoIdParamValidation,

  // Rate limiting
  apiLimiter,
  authLimiter,
  registerLimiter,
  passwordResetLimiter,
  bookingLimiter,
  paymentLimiter,
  messageLimiter,
  reviewLimiter,
  webhookLimiter,
  adminActionLimiter,
};
