const logger = require('./logger');
const {
  generateRandomString,
  generateReference,
  formatCurrency,
  formatDate,
  formatTime,
  formatDateTime,
  timeAgo,
  calculateDistance,
  toRadians,
  sanitizeInput,
  generateSlug,
  paginateArray,
  deepClone,
  pick,
  omit,
  isValidEmail,
  isValidPhone,
  truncateText,
  generateInitials,
  sleep,
  retryWithBackoff,
} = require('./helpers');

module.exports = {
  logger,
  generateRandomString,
  generateReference,
  formatCurrency,
  formatDate,
  formatTime,
  formatDateTime,
  timeAgo,
  calculateDistance,
  toRadians,
  sanitizeInput,
  generateSlug,
  paginateArray,
  deepClone,
  pick,
  omit,
  isValidEmail,
  isValidPhone,
  truncateText,
  generateInitials,
  sleep,
  retryWithBackoff,
};
